apiVersion: apps/v1
kind: Deployment
metadata:
  name: recurring-task-service
  labels:
    app: recurring-task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recurring-task-service
  template:
    metadata:
      labels:
        app: recurring-task-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "recurring-task-service"
        dapr.io/app-port: "8002"
    spec:
      containers:
      - name: recurring-task-service
        image: {{ .Values.registry }}/recurring-task-service:latest
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 8002
        env:
        - name: APP_PORT
          value: "8002"
